[target.wasm32-wasip1]
rustflags = ["-Clink-args=--no-entry --allow-undefined --export=main --export=malloc --export-table --import-memory --export-memory --strip-all"]

[target.wasm32-unknown-unknown]
rustflags = ["-Clink-args=--no-entry --allow-undefined --export=main --export=malloc --export-table --import-memory --export-memory --strip-all"]

[target.wasm32-unknown-emscripten]
rustflags = ["-Clink-args=-sERROR_ON_UNDEFINED_SYMBOLS=0 -sALLOW_MEMORY_GROWTH=1 -Wl,--whole-archive"]

[profile.release]
lto = true